services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - db
    networks:
      - symfony-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: sym64anthony
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - symfony-network

volumes:
  mysql-data:

networks:
  symfony-network:
    driver: bridge